### ISSUE TITLE
add the navbar and the footer to the [single news]

### ISSUE THREAD

**Issue by mo7amedehab97** [GSG-G11/news-team-2#25]
_task_

- create add the navbar to the single page [detail page ] 
- add the footer to the  single page [detail page ] 
- fix the style after adding the navbar and footer

**Comment by AhmedQeshta** [comment]
hi @mo7amedehab97 

## in the last section **Related Topics**, I suggest, decreasing margin-top to 0;
check it.

**this**
``CSS
@media (max-width: 375px)
.related-blog {
    display: flex;
    justify-content: center;
    align-items: center;
    width: 100%;
    margin: 50px 0 0 0;
}
``

**to** 

`@media (max-width: 375px)
.related-blog {
    display: flex;
    justify-content: center;
    align-items: center;
    width: 100%;
    margin: 0px 0 0 0;
}`

------------------------------------------------------------------
## another one, increase width card (Related Topics) like above cards to be same for all page

![image](https://user-images.githubusercontent.com/38624002/152111415-68c21ccf-3d92-4e8f-94ac-1af657444f6d.png)

#25

**Comment by AhmedQeshta** [comment]
Hi @mo7amedehab97 

in card Related : 
![image](https://user-images.githubusercontent.com/38624002/152120001-da2cc7a1-0bec-48ef-a868-ca3e435266c7.png)

### hint for help
`hr{
    background-color: #0000008f;
    border: none;
    height: 1px;
}
` 
#25

**Comment by AhmedQeshta** [comment]
Hi @mo7amedehab97 

### Add Animations For Image in **Related Topics**
#25

**Comment by AhmedQeshta** [comment]
Hi @mo7amedehab97 
@AhmedQeshta 

### Fix bug images In HTML 
by **removing `/` form source image**

- [ ] Remove ` <img src="/img/1.jpeg" alt="header image "> `  and add this `<img src="img/1.jpeg" alt="header image ">`
- [ ] Remove ` <img alt="Recommended for you" src="/img/recommended-for-you.png"> `  and add this `<img alt="Recommended for you" src="img/recommended-for-you.png">`
- [ ] Remove ` <img alt="Based on Like" src="/img/based-on-like.png"> `  and add this `<img alt="Based on Like" src="img/based-on-like.png">`

R #25
